In [3]:
import numpy as np

In [6]:
arr=np.array([1,2,3])

In [7]:
arr

array([1, 2, 3])

In [9]:
arr.dtype

dtype('int64')

In [10]:
print(type(arr))

<class 'numpy.ndarray'>


In [12]:
arr.ndim

1

In [13]:
# view bir dizinin görünümü oluşturur
x=arr.view()
arr[0]=5
print(arr)
print(x)

[5 2 3]
[5 2 3]


In [ ]:
#.base not niteliği döndürüyorsa orjinal dizidir


In [14]:
for x in arr:
    print(x)

5
2
3


In [16]:
arr_2=np.array([[1,2,3],[4,5,6]])
arr_2

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
for x in arr_2:
    for y in x:
        print(y)

1
2
3
4
5
6


In [19]:
arr_3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[1,2,3]]])
arr_3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [1, 2, 3]]])

In [20]:
for x in arr_3:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
1
2
3


In [21]:
# nditer() kullanılacak dizileri yineleme
for x in np.nditer(arr_3):
    print(x)

1
2
3
4
5
6
7
8
9
1
2
3


In [23]:
#ndenumerate() indis numaralarını vererek yineleme
for indis,x in np.ndenumerate(arr_3):
    print(indis,x)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(1, 0, 0) 7
(1, 0, 1) 8
(1, 0, 2) 9
(1, 1, 0) 1
(1, 1, 1) 2
(1, 1, 2) 3


In [24]:
# dizide arama where() metodu
x=np.where(arr_3==6)
print(x)

(array([0]), array([1]), array([2]))


In [25]:
newArr=np.array([1,2,3,4,5,6,7,8,9])
x=np.where(newArr%2==0)
x

(array([1, 3, 5, 7]),)

In [ ]:
# linespaces() metodu